/*
THIS PROJECT IS AN APPLICATION ON THE I2C PERIPHERAL.

AUTHOR: MARCELLINO ASHRAF

HARDWARE COMPONENTS:
1- STM32F103C8 MICRO-CONTROLLER TO RECEIVE FROM KEYPAD.
2- STM32F103C8 MICRO-CONTROLLER TO SEND TO LCD.

THIS PROJECT FILE HAS THE CODE FOR THE STM32F103C8 MICRO-CONTROLLER TO RECEIVE FROM KEYPAD.
*/

#include "LCD_DRIVER.h"
#include "DELAY.h"
#include "I2C.h"

void SystemInit(){}

int main(void)
{
	//SETUP
	LCD_init();
	I2C_INIT();
	LCD_command(LCD_clear);
	LCD_command(LCD_cursor_first_line);
	//LOOP
	while(1)
	{
		LCD_data(I2C_RECEIVE_BYTE());
		delay_ms(500);
	}
	return 0;
}
